"""
Bandwidth Meter - Measure human-AI collaboration efficiency.

Bandwidth = (Useful Information Transferred) / (Total Interaction Cost)

This module tracks per-session metrics:
- Signal quality (useful output vs total tokens)
- Corrections (human overrides)
- Time to productive (first valuable artifact)
"""

import json
from dataclasses import asdict, dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional


@dataclass
class BandwidthMetrics:
    """
    Per-session bandwidth metrics.

    These metrics measure the efficiency of human-AI collaboration
    during a single session.
    """

    # Core identifiers
    timestamp: datetime
    session_id: str
    project: str

    # Token metrics
    tokens_in: int = 0  # Context tokens injected
    tokens_out: int = 0  # Tokens generated by AI
    tokens_useful: int = 0  # Tokens accepted/used

    # Efficiency metrics
    corrections: int = 0  # Human overrides/fixes
    iterations: int = 0  # Edit cycles (higher = more refinement needed)
    time_to_productive_seconds: float = 0.0  # Time until first valuable output

    # Artifact counts
    files_modified: int = 0
    tests_passed: int = 0
    tests_failed: int = 0

    # Computed metrics
    @property
    def signal_ratio(self) -> float:
        """Ratio of useful tokens to total output tokens."""
        if self.tokens_out == 0:
            return 0.0
        return self.tokens_useful / self.tokens_out

    @property
    def compression_ratio(self) -> float:
        """How efficiently context was compressed (artifacts per input token)."""
        if self.tokens_in == 0:
            return 0.0
        return self.files_modified / (self.tokens_in / 1000)  # Per 1K tokens

    @property
    def correction_rate(self) -> float:
        """Corrections per iteration."""
        if self.iterations == 0:
            return 0.0
        return self.corrections / self.iterations

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        data = asdict(self)
        data["timestamp"] = self.timestamp.isoformat()
        # Add computed properties
        data["signal_ratio"] = round(self.signal_ratio, 3)
        data["compression_ratio"] = round(self.compression_ratio, 3)
        data["correction_rate"] = round(self.correction_rate, 3)
        return data

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "BandwidthMetrics":
        """Create from dictionary."""
        # Remove computed properties before creating instance
        data.pop("signal_ratio", None)
        data.pop("compression_ratio", None)
        data.pop("correction_rate", None)
        data["timestamp"] = datetime.fromisoformat(data["timestamp"])
        return cls(**data)


class BandwidthMeter:
    """
    Measures and tracks bandwidth metrics over time.

    Provides:
    - Per-session metric capture
    - Aggregate statistics
    - Trend analysis
    """

    def __init__(self, storage_dir: Optional[Path] = None):
        if storage_dir is None:
            storage_dir = Path.home() / ".cortex" / "research" / "bandwidth"

        self.storage_dir = storage_dir
        self.storage_dir.mkdir(parents=True, exist_ok=True)
        self.metrics_file = self.storage_dir / "bandwidth_metrics.jsonl"

    def record(self, metrics: BandwidthMetrics) -> None:
        """Record session bandwidth metrics."""
        with open(self.metrics_file, "a") as f:
            f.write(json.dumps(metrics.to_dict()) + "\n")

    def load_metrics(self, days: int = 7, project: Optional[str] = None) -> List[BandwidthMetrics]:
        """Load metrics from the last N days."""
        if not self.metrics_file.exists():
            return []

        cutoff = datetime.now() - timedelta(days=days)
        metrics = []

        try:
            with open(self.metrics_file, "r") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue

                    data = json.loads(line)
                    entry_time = datetime.fromisoformat(data["timestamp"])

                    if entry_time < cutoff:
                        continue

                    if project and data.get("project") != project:
                        continue

                    metrics.append(BandwidthMetrics.from_dict(data))

        except (json.JSONDecodeError, IOError) as e:
            print(f"Warning: Error loading bandwidth metrics: {e}")

        return metrics

    def get_aggregate_stats(self, days: int = 7, project: Optional[str] = None) -> Dict[str, Any]:
        """
        Calculate aggregate bandwidth statistics.

        Returns:
            Dict with aggregate metrics and trends
        """
        metrics = self.load_metrics(days=days, project=project)

        if not metrics:
            return {
                "sessions": 0,
                "avg_signal_ratio": 0.0,
                "avg_correction_rate": 0.0,
                "avg_time_to_productive": 0.0,
                "total_corrections": 0,
                "total_files_modified": 0,
            }

        total_signal = sum(m.signal_ratio for m in metrics)
        total_corrections = sum(m.corrections for m in metrics)
        total_iterations = sum(m.iterations for m in metrics)
        total_time = sum(m.time_to_productive_seconds for m in metrics)
        total_files = sum(m.files_modified for m in metrics)

        n = len(metrics)

        return {
            "sessions": n,
            "avg_signal_ratio": round(total_signal / n, 3),
            "avg_correction_rate": round(total_corrections / max(total_iterations, 1), 3),
            "avg_time_to_productive": round(total_time / n, 1),
            "total_corrections": total_corrections,
            "total_files_modified": total_files,
            "period_days": days,
            "project": project,
        }

    def compare_to_baseline(
        self,
        baseline_days: int = 30,
        recent_days: int = 7,
        project: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Compare recent metrics to baseline.

        Returns:
            Dict with deltas (positive = improvement)
        """
        baseline = self.get_aggregate_stats(days=baseline_days, project=project)
        recent = self.get_aggregate_stats(days=recent_days, project=project)

        if baseline["sessions"] == 0 or recent["sessions"] == 0:
            return {
                "signal_ratio_delta": 0.0,
                "correction_rate_delta": 0.0,
                "time_to_productive_delta": 0.0,
                "has_baseline": baseline["sessions"] > 0,
                "has_recent": recent["sessions"] > 0,
            }

        return {
            "signal_ratio_delta": round(
                recent["avg_signal_ratio"] - baseline["avg_signal_ratio"], 3
            ),
            "correction_rate_delta": round(
                baseline["avg_correction_rate"] - recent["avg_correction_rate"], 3
            ),  # Lower is better
            "time_to_productive_delta": round(
                baseline["avg_time_to_productive"] - recent["avg_time_to_productive"], 1
            ),  # Lower is better
            "baseline_sessions": baseline["sessions"],
            "recent_sessions": recent["sessions"],
        }


def get_session_metrics(
    session_id: str,
    project: str,
    tokens_in: int = 0,
    tokens_out: int = 0,
    tokens_useful: int = 0,
    corrections: int = 0,
    iterations: int = 1,
    time_to_productive_seconds: float = 0.0,
    files_modified: int = 0,
    tests_passed: int = 0,
    tests_failed: int = 0,
) -> BandwidthMetrics:
    """
    Create and record session bandwidth metrics.

    This is the main entry point for recording metrics.
    """
    metrics = BandwidthMetrics(
        timestamp=datetime.now(),
        session_id=session_id,
        project=project,
        tokens_in=tokens_in,
        tokens_out=tokens_out,
        tokens_useful=tokens_useful,
        corrections=corrections,
        iterations=iterations,
        time_to_productive_seconds=time_to_productive_seconds,
        files_modified=files_modified,
        tests_passed=tests_passed,
        tests_failed=tests_failed,
    )

    # Auto-save
    meter = BandwidthMeter()
    meter.record(metrics)

    return metrics
